version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle_cache:/usr/local/bundle
      - ./tmp/uploads:/app/public/uploads
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/aikidsfun_development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    stdin_open: true
    tty: true

  webpack:
    build: .
    command: bash -c "rm -f /app/public/packs/* && ./bin/webpack-dev-server"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle_cache:/usr/local/bundle
      - ./tmp/uploads:/app/public/uploads
    ports:
      - "3035:3035"
    depends_on:
      web:
        condition: service_started
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/aikidsfun_development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  # One-time service to fix Bundler version issues and dependencies
  bundle_update:
    image: ruby:2.4.10
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "gem install bundler -v 2.0.2 && bundle update mimemagic --conservative"

volumes:
  redis_data:
  bundle_cache:
  node_modules: 